### ISSUE TITLE
ModuleNotFoundError: No module named 'pyGF2'

### ISSUE THREAD

**Issue by BaseMax** [daniel-weisse/irreducible_polynom#1]
```
C:\Users\Max\irreducible_polynom>python irreducible.py
Traceback (most recent call last):
  File "C:\Users\Max\irreducible_polynom\irreducible.py", line 4, in <module>
    from pyGF2 import gf2_mul, gf2_div, gf2_add
ModuleNotFoundError: No module named 'pyGF2'
```

Hi there

It seems pyGF2 is https://github.com/popcornell/pyGF2.

Do you know how we can install its dependency to solve the problem and run it?

Thanks

**Comment by daniel-weisse** [comment]
I think the "correct" way would be to install the pyGF2 library [using pip](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-a-local-src-tree).
```shell
git clone https://github.com/popcornell/pyGF2
python3 -m pip install -e ./pyGF2
```

pyGF2 should then by globally available for your python programs.
You could also go the "lazy" way and just copy the `pyGF2` folder from https://github.com/popcornell/pyGF2 into the source of this repo and it should work

**Comment by BaseMax** [comment]
```
C:\Users\Max>cd pyGF2

C:\Users\Max\pyGF2>dir
 Volume in drive C has no label.
 Volume Serial Number is 0E60-C99C

 Directory of C:\Users\Max\pyGF2

11/13/2022  06:56 AM    <DIR>          .
11/13/2022  06:55 AM    <DIR>          ..
11/13/2022  06:56 AM            35,149 LICENSE
11/13/2022  06:56 AM    <DIR>          pyGF2
11/13/2022  06:56 AM             1,637 README.md
11/13/2022  06:56 AM             2,686 test_pyGF2.py
               3 File(s)         39,472 bytes
               3 Dir(s)  18,536,493,056 bytes free

C:\Users\Max\pyGF2>python -m pip install -e .
Obtaining file:///C:/Users/Max/pyGF2
ERROR: file:///C:/Users/Max/pyGF2 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by daniel-weisse** [comment]
Yes, seems like the pyGF2 repo is missing the required setup scripts to install it as a library.
You will have to copy the `pyGF2` folder from https://github.com/popcornell/pyGF2 into your source tree, then it *should* work.
